[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
test = "forge-test"
script = "script"
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "@uniswap/v4-core/=node_modules/@uniswap/v4-periphery/lib/v4-core/",
  "@uniswap/v4-periphery/=node_modules/@uniswap/v4-periphery/",
  "forge-std/=lib/forge-std/src/"
]
